version: '3'
services:
  fivem-server:
    container_name: fivem
    image: brnelsons/fivem-dedicated-server:latest
    ports:
      - "40120:40120"
    depends_on:
      - fivem-db
  fivem-db:
    container_name: fivem-db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  data: